### ISSUE TITLE
Dual-Boot Windows10/FydeOS on a nvme ssd 

### ISSUE THREAD

**Issue by DarkSiider77** [imperador/chromefy#102]
hello,
I wish to create a dual-boot on my laptop FydeOS/W10 with rEFInd but i'm confuse because there are many tutorial about this subject and many are out of date or badly written/confuse. So i would have a guide with clear and correct instruction (i'm experiment) to install fydeOS in dual-boot with W10. If needed i can reinstall W10.
thank you in advance for all the help that will be given

**Comment by vemoxy** [comment]
@DarkSiider77 what are you confused about? The only step that needs to be changed is the dual boot install command in the [Dualbooting guide](https://github.com/imperador/chromefy/blob/master/lab/DualBoot.md):

```
sudo bash /usr/sbin/dual-boot-install -d /dev/nvme0n1
```

**Comment by DarkSiider77** [comment]
The script dualboot.sh doesn't work with the last version of fyde os, the error is: No system partition found

**Comment by DarkSiider77** [comment]
and there are many method outdate to dualboot fyde os with windows 10 and there are issue about ssd nvme and fydeos in the github of project croissant. It is the reason why i'm confused!

**Comment by DarkSiider77** [comment]
And when I execute the command sudo bash /usr/sbin/dual-boot-install -d /dev/nvme0n1 he doesnt found the script but i will retry with a clear installation. Thanks for the answer !

**Comment by DarkSiider77** [comment]
I bloked already to dual-boot because all methods have I used fail with fydeos and now the method constiting to patch the image with dualboot.bin doesn't work for me.
So have you any idea to install or dual-boot fyde os with win10

**Comment by DarkSiider77** [comment]
And the extension buil-in to dual-boot fyde-os isn't work because the installation of extension failed because the extension isn't update.

**Comment by DiogoSilva48** [comment]
This is not for FydeOS.
