### ISSUE TITLE
Raspberry Pi 3

### ISSUE THREAD

**Issue by puccaso** [imperador/chromefy#11]
Aweosme work here!

qq - there are official versions of chrome for ARM, however - can we get this working on the Raspberry pi?

i have both the 3b and 3b+ and neither boots...

**Comment by imperador** [comment]
There is another project (that we are not affiliated with), that focus on getting Chromium OS working on Raspberry Pi 3B/3B+:

https://github.com/FydeOS/chromium_os_for_raspberry_pi
