### ISSUE TITLE
after .img completed, File handle is not closed

### ISSUE THREAD

**Issue by kisChang** [imperador/chromefy#110]
using Option 1, File handle is not closed after production is completed, .img can't using write.
code version : master
host OS: ubuntu 18.04

**Comment by dragon788** [comment]
Are you building the image on a removable disk or an internal drive and is the internal drive an SSD?

**Comment by kisChang** [comment]
emmmm
I am using a virtualbox run ubuntu , with share windows10 work directory

**Comment by dragon788** [comment]
I would move the files outside of the shared directory to do the combining, and then just copy it into the shared directory once everything is done. Most shared directories don't have great performance, and they also tend to mess up the permissions of files there so that could be part of the issue.

**Comment by kisChang** [comment]
Estimated to be a shared directory issue.
