### ISSUE TITLE
Chrome OS installation isn’t detected

### ISSUE THREAD

**Issue by b33p-sh33p** [imperador/chromefy#112]
So I just installed Chrome OS on my computer (MacbookPro9,2) using Method 1, and the installation doesn’t seem to be detected (I get the blinking folder with the question mark). I tried using the fix-grub script, to no avail. Please help.
Edit: I think that maybe it’s not that it isn’t detected, but that it isn’t bootable.

**Comment by DiogoSilva48** [comment]
Does it boot with Regular Chromium non-"Chromefied" ???
