### ISSUE TITLE
Can't get pass the Login

### ISSUE THREAD

**Issue by TR-B** [imperador/chromefy#127]
I installed it on my Lenovo ThinkPad 13 with Metohd 1 and the installation worked perfectly fine but when I try to setup my new "Chromebook" and type in my email and password the Login is accepted, then the next screen states "please wait" and will not load. "Spins" endlessly.

I tried to use diffrent combinations:
1. with eve and ArnoldTheBat (Vanilla)
2. with pyro and ArnoldTheBat (Vanilla)
3. with pyro and FydeOS

The installtion works perfectly fine I just can't get pass the Login.

**Comment by GabWas** [comment]
I had the same problem. For me, using the TPM2 emulator ([swtpm.tar](https://github.com/imperador/chromefy/raw/master/swtpm.tar)) solved the issue.

**Comment by TR-B** [comment]
> 
> 
> I had the same problem. For me, using the TPM2 emulator ([swtpm.tar](https://github.com/imperador/chromefy/raw/master/swtpm.tar)) solved the issue.

Thanks a lot it now runs perfectly fine.
