### ISSUE TITLE
Cannot Boot

### ISSUE THREAD

**Issue by homemaint** [imperador/chromefy#132]
I have an AMD A4-4000 processor computer. When I boot into the USB of image made by method 1 (eve image), it shows grub where 5 options could be seen:

1. local disk A
2. local disk b
3.verified disk A
4. verified disk B
5. Alternate USB boot 
 
But it does not load with any option and my caps lock and scroll lock LEDs blink continuously. I tried many times with two different images. Help me as soon as possible.

**Comment by khanhtranngoccva** [comment]
e2fsck /dev/sda(b/c)3? That would do.

**Comment by khanhtranngoccva** [comment]
By the way, AMD devices are not supposed to run Chromium or Chrome.

**Comment by stopislam** [comment]
AMD device should try cloudready OS

**Comment by homemaint** [comment]
Thank you for the help.
