### ISSUE TITLE
Cannot boot into USB

### ISSUE THREAD

**Issue by homemaint** [imperador/chromefy#133]
I have an AMD A4-4000 processor computer. When I boot into the USB of image made by method 1 (eve image), it shows grub where 5 options could be seen:

1. local disk A
2. local disk b
3.verified disk A
4. verified disk B
5. Alternate USB boot 
 
But it does not load with any option and my caps lock and scroll lock LEDs blink continuously. I tried many times with two different images. Help me as soon as possible.

**Comment by homemaint** [comment]
Please help me ASAP!

**Comment by homemaint** [comment]
Which images are recommended for the above processor?

**Comment by xeu100** [comment]
I'm having similar issues with the AMD Ryzen 3500U processor, except it's stuck on "local image A".

**Comment by homemaint** [comment]
I tried the same image on my Intel laptop, and it worked, but it is not working with AMD processor. IN the laptop I also have Windows 10 and I wanted to multiboot, but the commands which I saw on the net were not promising. I know how how to properly multiboot.

**Comment by stopislam** [comment]
AMD laptops should Try Cloudready OS.

**Comment by xeu100** [comment]
> AMD laptops should Try Cloudready OS.

The whole point of using Chromefy is to get all the features of ChromeOS... Cloudready doesn't have nearly as many features. Cloudready isn't compatible with chromefy either.

**Comment by khanhtranngoccva** [comment]
AMD can't try Chromefy by the way. The best you can do is to build an Android 10 container into Cloudready and upload scripts, etc.

**Comment by khanhtranngoccva** [comment]
And I lost all data on my PC due to problems with Cloudready.

**Comment by xeu100** [comment]
> AMD can't try Chromefy by the way. The best you can do is to build an Android 10 container into Cloudready and upload scripts, etc.

> And I lost all data on my PC due to problems with Cloudready.

Chromefy doesn't work with AMD *yet*, this issue is meant to raise awareness. I can't attest to the data loss on Cloudready, but it is a very stable platform meant for non-techy people and organizations.

**Comment by homemaint** [comment]
> AMD can't try Chromefy by the way. The best you can do is to build an Android 10 container into Cloudready and upload scripts, etc.

How to do that?

**Comment by xeu100** [comment]
> > AMD can't try Chromefy by the way. The best you can do is to build an Android 10 container into Cloudready and upload scripts, etc.
> 
> How to do that?

You can't, they were saying that the best way would just be making it and uploading it for others.

**Comment by homemaint** [comment]
Okay thanks, closing issue.
