### ISSUE TITLE
Question: is it working on AMD now?

### ISSUE THREAD

**Issue by Lukasz-egg** [imperador/chromefy#160]
Is there any version of recovery etc. to download to work on AMD proccessor? If no, what's best replacement for Chrome os? (I like to have Play store, cloudready doesn't support it)

**Comment by neptalactone** [comment]
If your main goal is to have play store, have you tried any android-based OS like Androidx86 or BlissOS?

**Comment by Lukasz-egg** [comment]
> If your main goal is to have play store, have you tried any android-based OS like Androidx86 or BlissOS?

Yeah, I now have android x86 installed, but i like to try chrome OS so that's why i asked question, but now i know that there is 1 image that can run, but not always, and on my laptop not working ://
