### ISSUE TITLE
(question) what is this actually?

### ISSUE THREAD

**Issue by rinaldohack** [imperador/chromefy#22]
from what I understand, this somehow merge chromium os with chrome os. correct? basically hackintosh, but chrome os? 

also generating your chrome imgs : you said "We won't provide the imgs." Why? Is this is not the easiest way?

**Comment by alesimula** [comment]
Yes, this is basically hackrome OS.

We don't provide images for two main reasons:

1) The compatibility may vary depending on the chromium build used (ATB, Fyde, etc)

2) (most importantly) copyright infringement; the script is also able to generate a chromefied image, but we don't encourage sharing it online
