### ISSUE TITLE
"Hanging" at G Symbol boot-screen

### ISSUE THREAD

**Issue by modzilla99** [imperador/chromefy#25]
Hey there,

When using the eve and caroline (for tpm) images as base, the system will hang there... Tho when pressing  Ctrl + Alt + F2 it will launch the console just fine and I can log in as root! I'm using the Dell Latitude 5580 btw

**Comment by modzilla99** [comment]
Seems to be related to arnoldthebats builds

**Comment by balajivijay-tech** [comment]
Whether you used fyde os  as base or not?

**Comment by modzilla99** [comment]
I did and then it started working
