### ISSUE TITLE
Malware warning on  chrome.qwedl.com

### ISSUE THREAD

**Issue by DennisLfromGA** [imperador/chromefy#3]
When following the guide: '[Getting the right IMG for YOUR  @pc](https://github.com/imperador/chromefy#getting-the-right-img-for-your-pc)'
and attempting to navigate to [chrome.qwedl.com]( chrome.qwedl.com) I get the following warning from my router:

![screenshot 2018-11-16 at 11 01 44 am](https://user-images.githubusercontent.com/3418772/48632704-94bfe800-e98f-11e8-975d-e71d83cce8ea.png)

I think it would be better to obtain the image from the [cros-updates](https://cros-updates-serving.appspot.com/#eve) site. You can obtain *official* recovery images for the last few versions under the 'Recovery' column for each boardname / device.

-**DennisLfromGA**

**Comment by imperador** [comment]
Already changing it at the tutorial

**Comment by imperador** [comment]
Fixed at [f75b3c6](https://github.com/imperador/chromefy/commit/f75b3c6aaca4e377ff3f27885ed4bed1c46e32d9). Closing the issue
