### ISSUE TITLE
Black screen when android apps are under windows.

### ISSUE THREAD

**Issue by fatihbalsoy** [imperador/chromefy#37]
### Issue:
The screen blinks, completely black, three to five times every time an Android App is covered by another window (ChromeOS/Android/Linux, doesn't matter). After the obnoxious blinking, the Android virtualization would crash and shell/GUI would restart. Literally shutting down the Android and Linux environments and keeping ChromeOS still running.

This could be a problem in ChromiumOS itself, the Chromefy hack, or the laptop's video driver. I just wanted to post this for possible fixes that might help everyone else having the same issue.

### Device and Recovery Images:
Two months ago (Nov. 2018), I successfully installed an ArnoldTheBat build of **_v69_** on a **_Dell Inspiron 11 3138_** with **_Eve and Caroline recovery images_**. Everything seemed to work fine and no issues.

Anyway, when I came back to the XDA thread (Dec. 2018) to see any workarounds for Chrome OS updates, I saw the new method and tried it out to install **_v70_**. Everything seemed fine until I opened the Google Play Store, this issue occurred.

Today (Jan. 2019), I came back to this repository and tried out option 2a to install **_v71_**. Everything worked fine and the system was much faster than before, but the blinking screen issue was still existent to this day.

**Comment by alesimula** [comment]
Have you tried switching to ATB v71 base (over v69)?

**Comment by fatihbalsoy** [comment]
My previous config, without the issue, was ChromeOS v69 installed over an ATB v69. 

Currently it's ChromeOS v71 over ATB v72 (There was no v71 build). I'll try a different ChromiumOS build when I have the time.

Does both versions of ChromiumOS and ChromeOS have to be the same?

**Comment by fatihbalsoy** [comment]
@alesimula @imperador
I found a temporary fix to this issue:
If you turn on night shift/mode, it prevents the display from flickering. This issue only occurs when night shift is not turned on.

If anyone's having this same issue, you can turn on night mode forever and manually adjust the screen temperature from settings rather than automatically.
