### ISSUE TITLE
no chrome://flags visible after successful installation

### ISSUE THREAD

**Issue by lug9417** [imperador/chromefy#40]
Problem: 
I have a Dell Venue Pro 11 7140. I installed Chrome OS on it following the tutorial.

I'm very unsure if this is even the right place for this issue or if it is a chrome os bug but:

When I navigate to chrome://flags I'm only presented with the site's top part with the searchbar but no flags that I can enable. Everything below the search bar is just empty. Typing in the searchbar changes nothing.

What I tried so far to fix it based on answers I found googling (but nothing worked):

- Launch Incognito mode and go to chrome://flags -> no change

- launch guest session from login screen -> flags are visible, changes apply to current session, but are not persisted to my user account

- powerwash -> no change

- log in with a second gmail account that I have -> also see no flags

If this has nothing to do with the "chromification" process an is a chrome bug, just let me know and close this issue.

**Comment by HiItsDevin** [comment]
Can confirm that it's not working for me either. Pretty annoying.

**Comment by NSbuilder** [comment]
Not working for me either...

**Comment by NSbuilder** [comment]
Also: Can't enable debugging features which gives an error.

**Comment by fishgrind** [comment]
same problems here, flags are empty only the search and reset is available, and installing Linux fails with, "Error starting virtual machine"

Dell Venue 11 Pro

**Comment by MuntashirAkon** [comment]
Not working for me either.

**Comment by MuntashirAkon** [comment]
According to a [dev](https://bugs.chromium.org/p/chromium/issues/detail?id=391357#c23), **chrome://flags** doesn't show up if the command-line switches did not match the flags (in general). Then he said ignoring "signin profile" should fix it. I don't know what "signin profile" really means, but as far as I understand, it's something to do with user login, which is why it doesn't affect the guest mode.

Since you can easily add a flag using `/etc/chrome_dev.conf`, it doesn't really matter if flags shows up there or not.

**Comment by NSbuilder** [comment]
>  as far as I understand, it's something to do with user login
![Annotation 2019-03-12 004911](https://user-images.githubusercontent.com/8482453/54163173-ca1da380-4460-11e9-8957-e0dfc2217ebf.jpg)

Maybe it has to do with the way the image was created? I used CAROLINE image instead of the TPM emulator.

**Comment by MuntashirAkon** [comment]
> Maybe it has to do with the way the image was created? I used CAROLINE image instead of the TPM emulator.

I don't think so. There's [an active issue](https://github.com/arnoldthebat/chromiumos/issues/238) in the @arnoldthebat's repo which describes the same problem.

**Comment by NSbuilder** [comment]
Maybe we will have to try another Chromium distribution

**Comment by NSbuilder** [comment]
https://forum.xda-developers.com/hardware-hacking/chromebooks/blank-empty-chrome-flags-page-t3911200

**Comment by fishgrind** [comment]
@NSbuilder cheers that solved it for me on my Dell Venue 11 Pro 7130

**Comment by MuntashirAkon** [comment]
> It seemse to have something to do with TPM ( again... [#38 (comment)](https://github.com/imperador/chromefy/issues/38#issuecomment-471211390))

In my case, TPM is working on Windows 10 as expected but not on Chrome OS. On Ubuntu, however, I'm getting the following error:

```log
tpm_crb MSFT0101:00: [Firmware Bug]: ACPI region does not cover the entire command/response buffer.
```

Perhaps, TPM is Microsoft only?

> @NSbuilder cheers that solved it for me on my Dell Venue 11 Pro 7130

How did you solve it?

**Comment by fishgrind** [comment]
@MuntashirAkon it depends on your bios.

I have TPM enabled, PTT disabled, and for TPM I only have it enabled I didn't enable TPM ACPI

Then again I have a Dell 7130, your Bios may be different.

**Comment by Crescendo-BLYAT** [comment]
Need to use **swtpm2.tar**, currently working with ATB72 special build or FydeOS 6.0 or ATC v3...

Mine's working: ATB72 Special + Eve 73 + **swtpm2.tar**

Can't do with Caroline ot hardware TPM on your laptop (can't even take ownership of the chip no matter what).

**Comment by kbnhvn** [comment]
@Crescendo-BLYAT

The latest swtpm from this git?

**Comment by Crescendo-BLYAT** [comment]
> @Crescendo-BLYAT
> 
> The latest swtpm from this git?

exactly....

**Comment by Crescendo-BLYAT** [comment]
@arnoldthebat please include this in all of your builds to fix this flags issue for good: https://github.com/imperador/chromefy/blob/master/swtpm.tar

Its the only way that can work coz the BIOS of most laptop doesn't allow ownership takeover by non-windows OS.

**Comment by arnoldthebat** [comment]
Will do! I just need to get the time to make the ebuild to slipstream it
into the build....

**Comment by erenoglu** [comment]
Hi @Crescendo-BLYAT, with swtpm, did ChromeOS take ownership of the software TPM? Or is it just able to create some root keys? (SRK etc.)   I think the command shall be something like "trunks_client --status"

**Comment by Crescendo-BLYAT** [comment]
@erenoglu yes, it take ownership of the swTPM as the prob here is the OS unable to take ownership (or even access) the hwTPM...

**Comment by erenoglu** [comment]
Yes. I wonder why chromeos is not able to take ownership of the hardware module though, while it can for the swtpm.

I tried a lot, reset from windows, from Linux, from bios, none worked for me. 

HW TPM is partially usable and chromeos creates SRK etc but not owned.

**Comment by arnoldthebat** [comment]
Ah this could be my lack of understanding. Are you saying, even with
Hardware TPM, ChromiumOS fails to own it? So I would be better with
software TPM regardless of whether the device supports hardware?

**Comment by erenoglu** [comment]
Exactly, I have a TPM 2.0 hardware module driven by tpm_tis module. It works with Windows and Linux. In ChromeOS or ChromiumOS or FydeOS, after a BIOS clear, the tpm_tis module is loaded, and some root keys are installed on it and I can login to my system, but the TPM is never owned, hence it's not 100% working.  

I'll try today once more, but I think there are others in my situation, that's why keeping vtpm module in kernel and having swtpm in the build would not hurt in my opinion. the vtpm service can be disabled / commented out by default and the affected people can turn it on manually.

**Comment by arnoldthebat** [comment]
OK, let me build a variant with the SWTPM installed and enabled, then we
can run with both versions.

**Comment by GuzioMG** [comment]
As far as I know, you need to open chrome://flags in incognito mode. This fixed my issue with ArnoldTheBad, however, I'm not sure, will this also fix this problem on Chromefied CrOS.

**Comment by erenoglu** [comment]
So the latest on this is that the swtpm package with the vtpm service file works well, if you disable the TPM from BIOS and also blacklist its module & make a /bin/false module install.  
/etc/modules.d/tpm.conf  (for tis module)
```
install tpm_tis /bin/false
blacklist tpm_tis
```
Then the swtpm works at first boot and provides the tpm functions. All ChromeOS functions which require a TPM then starts working, including the chrome://flags

**Comment by MuntashirAkon** [comment]
I think this problem is solved and safely closed.

**Comment by erenoglu** [comment]
Hi all, I see some new but critical commits in the swtpm original github page which also fixes some functions like below. I'm having trouble using it with new R76 images, so maybe could help:
swtpm: Use writev_full rather than writev; fixes --vtpm-proxy EIO error...

Could anybody build a new swtpm.tar version from master branch?
https://github.com/stefanberger/swtpm
