### ISSUE TITLE
EFI partition nonexistent/empty after boot

### ISSUE THREAD

**Issue by haydennyyy** [imperador/chromefy#48]
So I installed it, but... There's no GRUB. And I tried to run the scripts but there's no EFI partition found.

**Comment by lovelydumpling** [comment]
Experiencing the same problem. "Missing OS". Run the grub line, and it mentions there being no EFI partition.

**Comment by rsdkz** [comment]
Same issue here. Really disappointed. It also normally boots from USB.

**Comment by lovelydumpling** [comment]
I used chromefy.sh from Project Croissant v2.1 in the Releases build. I renamed it to croissant.sh so I could do the command as instructed.

**Comment by dracinn** [comment]
I used the croissant.sh found on the main GitHub page, I recommend doing the Chromium 2A install method then use 2B in the future to update your system.

**Comment by haydennyyy** [comment]
So I basically did a clean reinstall and it worked. Sorry guys! I reinstalled ATB's build and used the image to build the installer USB for ChromeOS and went from there

**Comment by lovelydumpling** [comment]
Well, that's cool. But I've done that multiple times to no avail :/

I'll look into trying the 2A method.

**Comment by lovelydumpling** [comment]
Going with Option 2A and using swtpm.tar instead of Caroline provided a successful result. Thanks guys!

Also had to look up linux commands. Last time I tried to do 2A I couldn't figure out how to run the script from the terminal haha
