### ISSUE TITLE
No Linux Apps

### ISSUE THREAD

**Issue by nathanandtech** [imperador/chromefy#49]
Android Apps are working fine, but no option for Linux apps under settings.

Using Eve 72, with Caroline 72 for TPM fix. 

Also cannot see the flags, so I guess the TPM is not working still, would this cause no Linux apps? 

Otherwise working well on HP X2 Elite G1.

**Comment by zZSETHzz** [comment]
Have you enabled Linux at all within the settings? Linux needs enabling within the settings first before you can do anything at all as its missing the container by default and needs to install it.

**Comment by nathanandtech** [comment]
I can't see the setting even, only the play store one. do I need developer mode?

**Comment by zZSETHzz** [comment]
yes, when booting into ChromeOS and you see the GRUB screen of selecting image a or b etc.... press e and make sure one of the boot parameters specified is cros_debug, if not, add it in.

**Comment by nathanandtech** [comment]
cros_debug is already there, between cros_efi and root=partUUID etc etc.

**Comment by nathanandtech** [comment]
I booted back up to the USB and install the nocturne image to see if that made a difference, same deal, I get the play store but no linux apps. 
Is this because I used caroline for the TPM and caroline doesn't support linux?

**Comment by nathanandtech** [comment]
OK I reset the bios and re-enabled VT-x settings and it has shown up, thanks for all the help guys.
