### ISSUE TITLE
Automating the Dual Boot process

### ISSUE THREAD

**Issue by imperador** [imperador/chromefy#5]
Create a script to deploy the dualboot option into a chrome build

**Comment by TophC7** [comment]
Hi i tried this method and all seem to work until i try to install it to my main drive.

I believe the problem is that it's always assumed that /dev/sda is the main drive but in my case the main drive is /dev/nvme0n1

**Comment by imperador** [comment]
This is still experimental. It is not working yet

**Comment by imperador** [comment]
Solved at [Commit 132c2de](https://github.com/imperador/chromefy/commit/132c2dedc1caba27f35e832b22da3a2297cf448f). Will be released at the next version of the script
