### ISSUE TITLE
"Missing OS"

### ISSUE THREAD

**Issue by Gagnef03** [imperador/chromefy#51]
So, after a succesfull install my PC says "Missing OS", so I tried running the "curl  -L  https://goo.gl/HdjwAZ   |  sudo  bash  -s  /dev/sda" but I don't have any wifi, is there any way I could run it without internet maybe?

**Comment by venkatdevu** [comment]
i have same issue, you completed install...

**Comment by 0xCTF** [comment]
same error, did you found a sloution please ?
