### ISSUE TITLE
\r: command not found

### ISSUE THREAD

**Issue by GuzioMG** [imperador/chromefy#58]
Actually, after buying new SSD (because Dual boot isn't yet automated by script & I didn't want to lose my files), years of trying to have all files accessible during the installation process and looking for required recovery images, I was ready to do it. So I typed `sudo bash chromefy.sh` with all required params (path to `caroline.bin`, etc.). And pressed `ENTER`. And... BOOM! This error:
`chromefy.sh: line 2: $'\r': command not found`
`chromefy.sh: line 6: $'\r': command not found`
`chromefy.sh: line 11: $'\r': command not found`
`chromefy.sh: line 15: $'\r': command not found`
`chromefy.sh: line 27: syntax error near unexpected token '$'{\r''`
`'hromefy.sh: line 27: 'function cleanup_chromefy {`. I have no idea, what does it mean (Some sort of compilation error?), because I never learned bash ( #OnlyObjectPrograming ), but I would be happy if you tell me what's going on.
![bitmoji](https://render.bitstrips.com/v2/cpanel/99e3cf02-4018-4d07-a15e-e61a138217f0-adafaadc-4555-4b2b-807d-942032e2e7cc-v1.png?transparent=1&palette=1&width=246)
Thank you!

**Comment by dragon788** [comment]
What operating system are you using to attempt to create the image?

**Comment by GuzioMG** [comment]
I'm directly on Chromium OS. ArnoldTheBat build distro.

**Comment by GuzioMG** [comment]
And what do you mean by
> to create the image
?

All images (i. e. Caroline.bin and eve.bin) were downloaded from https://cros-updates-serving.appspot.com/ website, as suggested on README.MD file. Is chromefy.sh generating image? Isn't it changing Chromium OS to make it think, it's Chrome OS?

**Comment by GuzioMG** [comment]
> Actually, I can try method nr. 1, since it run on Linux and that sounds promising. Maybe Linux will have \r command.

Hell yeah!!!! It's going!!!

![image](https://user-images.githubusercontent.com/35845447/59563856-7dd59700-903f-11e9-8e04-83b6a1b12218.png)
