### ISSUE TITLE
Dual boot and recovery

### ISSUE THREAD

**Issue by refi64** [imperador/chromefy#68]
This admittedly isn't as much of an "issue" as a question I'm a bit concerned about. I had once dual-booted with Chromium OS on an external hard drive shared with some other data, and then when I was messing with my core config files, Chromium OS decided to do a recovery mode and...completely wipe the entire hard drive.

I'd like to look into dual booting again, but this is something I'm still concerned about. Does chromefy do anything to try to avoid this?

**Comment by zZSETHzz** [comment]
We do not alter the processes or operation of ChromeOS with this. Any recovery that happens is part of the OS and functions as intended. We have no plans to change this.

There is always risk associated with messing around with an OS and as such all we can do is advise you be more careful with what you mess around with.

**Comment by refi64** [comment]
Indeed, I did learn that :sweat_smile: The reason was that the touchpad had some issues and I was writing some manual hwdb rules to try and fix it, but apparently I massively screwed something up. My current system doesn't do that, so it's not *as* much of a concern, but I just have nightmare scenarios playing out in my head where e.g. something internally breaks and massively wipes everything in retaliation.

Thanks for the response though.
