### ISSUE TITLE
cannot use ethernet

### ISSUE THREAD

**Issue by chanhyokpark** [imperador/chromefy#70]
I created my ChromeOS image with chromefy(32bit, pyro V72), and I booted with USB. it cannot see Broadcom lancard, so I connected the ethernet, but it can't see that either. 
how can I fix this problem? 

my specs: Intel CPU, Broadcom WLAN card, Samsung q330, Yukon ethernet

**Comment by dragon788** [comment]
Did you use the ArnoldTheBat Vanilla image or the Special image? I have a feeling you used the Vanilla which doesn't include a lot of extra drivers. Try again with the Special image and you should have more success, as I've not run into much that isn't recognized with the Special image yet.

**Comment by chanhyokpark** [comment]
thanks. I used the FydeOS image, and I'll try it later with an ArnoldTheBat special image.
