### ISSUE TITLE
Installing ChromeOS Recovery Results in System Freeze

### ISSUE THREAD

**Issue by mikestan** [imperador/chromefy#71]
I've successfully gotten chromium to install from the ArnoldTheBat special image (file: Cx86OS_R60-9592.B-Special.7z) and yet when I use croissant.sh to either make my final Chromebook image OR apply the recovery/TPM a reboot consistently results in my system hanging and the CAPS LOCK flashing. 

I've tried using eve v74 and v71 as well as caroline v74 and v71 and I am working on a Lenovo Yoga 2 Pro.

Thoughts on how to get this working?

**Comment by zZSETHzz** [comment]
This is a kernel panic, the best bet is to try creating your image using a different base Chromium OS. FydeOS is probably your best bet here

**Comment by asapkota** [comment]
Same here. Works perfectly fine with ATB72 but hangs on ATB74. For me, there is no kernel panic since I can CTRL+C and exit the script and try again or do other things. Thoughts?

**Comment by zZSETHzz** [comment]
> Same here. Works perfectly fine with ATB72 but hangs on ATB74. For me, there is no kernel panic since I can CTRL+C and exit the script and try again or do other things. Thoughts?

I believe this is a different issue. The OP is saying the system hangs upon boot, whereas you've mentioned a script which shows your issue is with creating the image instead. This isn't actually an issue and appears to be something with your computer specifically as everyone else is fine with building. Please join the telegram group for real time help from us devs and the community.: t.me/chromeosforpc

**Comment by dragon788** [comment]
I would HIGHLY recommend grabbing the Camd64 image instead of the Cx86 as the 32 bit stuff isn't really supported by Google anymore and probably isn't very well tested either.

**Comment by mikestan** [comment]
> I would HIGHLY recommend grabbing the Camd64 image instead of the Cx86 as the 32 bit stuff isn't really supported by Google anymore and probably isn't very well tested either.

OK, it sounds like my choice of images may be the issue. I'll try again with different images (going to take awhile to complete), starting ATB72 for Camd64. Thanks, all!

**Comment by mikestan** [comment]
YES - I finally got it to work! For the record, my Lenovo Yoga 2 Pro is running ATB72 for Camd64, eve v72, and caroline v72, which I installed via procedure 2a on this GitHub. Many thanks for everyone's input.

I'll called this one user error in trying to find a combination of images needed to work on my HW.
