### ISSUE TITLE
This Chromium image does not support VTPM proxy, use different image or TPM replacement method

### ISSUE THREAD

**Issue by chanhyokpark** [imperador/chromefy#73]
hello? I used arnoldthebat special img cx86os v60 and pyro v62 recovery file and swtpm.tar, then I have this error:
localhost / # cd home/chronos/user/Downloads/chromefy
localhost /home/chronos/user/Downloads/chromefy # sudo bash chromefy.sh chromium.img recovery.bin swtpm.tar
This Chromium image does not support VTPM proxy, use different image or TPM replacement method
how can I fix it?

**Comment by busybox11** [comment]
How did you fixed this?

**Comment by chanhyokpark** [comment]
I used caroline image

**Comment by busybox11** [comment]
Thank you, it worked for me too.
