### ISSUE TITLE
mount: wrong fs type, bad option, bad superblock on /dev/loop7,        missing codepage or helper program, or other error         In some cases useful info is found in syslog - try        dmesg | tail or so. umount: /tmp/install-mount-point: not mounted

### ISSUE THREAD

**Issue by chanhyokpark** [imperador/chromefy#75]
I used camd64 os v69 and pyro v69 and caroline v69 then I installed it and I have:
![Screenshot 2019-06-23 at 9 12 02 AM - Display 1](https://user-images.githubusercontent.com/49719798/59970022-15366f00-9597-11e9-8b28-02d2dd6dc662.png)
what can I do?

**Comment by chanhyokpark** [comment]
here is my lsblk 

├─sdb4                                                    8:20   0    16M  0 part 
├─sdb10                                                   8:26   0   512B  0 part 
├─sdb2                                                    8:18   0    16M  0 part 
├─sdb9                                                    8:25   0   512B  0 part 
├─sdb7                                                    8:23   0   512B  0 part 
├─sdb5                                                    8:21   0     4M  0 part 
├─sdb11                                                   8:27   0     8M  0 part 
├─sdb3                                                    8:19   0     4G  0 part /
├─sdb1                                                    8:17   0     4G  0 part /mnt/stateful_partition
├─sdb8                                                    8:24   0    16M  0 part /usr/share/oem
├─sdb6                                                    8:22   0   512B  0 part 
└─sdb12                                                   8:28   0    32M  0 part 
loop6                                                     7:6    0 206.9M  1 loop 
└─3108E575226195CFCD07C10A9AB2C6E046C4EFA672EDBC0FB28C265855E1E26E
  254:1    0 205.3M  1 dm   /run/imageloader/cros-termina/10895.46.0
loop4                                                     7:4    0     4K  1 loop /opt/google/containers/arc-obb-mounter/mountpoints/container-root
sr0                                                      11:0    1  1024M  0 rom  
loop2                                                     7:2    0     4K  1 loop /opt/google/containers/arc-removable-media/mountpoints/container-root
loop0                                                     7:0    0   1.2G  0 loop 
└─encstateful                                           254:0    0   1.2G  0 dm   /mnt/stateful_partition/encrypted
sda                                                       8:0    0 465.8G  0 disk 
├─sda4                                                    8:4    0    16M  0 part 
├─sda2                                                    8:2    0    16M  0 part 
├─sda12                                                   8:12   0    32M  0 part 
├─sda9                                                    8:9    0   512B  0 part 
├─sda10                                                   8:10   0   512B  0 part 
├─sda7                                                    8:7    0   512B  0 part 
├─sda5                                                    8:5    0     2G  0 part 
├─sda3                                                    8:3    0     2G  0 part 
├─sda1                                                    8:1    0 461.6G  0 part 
├─sda11                                                   8:11   0     8M  0 part 
├─sda8                                                    8:8    0    16M  0 part 
└─sda6                                                    8:6    0   512B  0 part 
zram0                                                   253:0    0     4G  0 disk [SWAP]
loop5                                                     7:5    0  46.2M  1 loop 
loop3                                                     7:3    0     4K  1 loop /opt/google/containers/arc-sdcard/mountpoints/container-root

**Comment by chanhyokpark** [comment]
oh I used dd command and worked

**Comment by mesbahulalam** [comment]
> 
> 
> oh I used dd command and worked

Wait, tell us more, how did you use the dd command? What did you use as the arguments?

**Comment by chanhyokpark** [comment]
I cannot remember... Only thing that I remember is that I looked up Wikipedia to find the command. I used the command at developer mode.

**Comment by chanhyokpark** [comment]
+ If you use this method, the data disk partition will be too small. You need to use live Gparted.
