### ISSUE TITLE
Where download caroline.bin?

### ISSUE THREAD

**Issue by iHad169** [imperador/chromefy#8]
Where download caroline.bin?
I cannot find.

**Comment by iHad169** [comment]
https://dl.google.com/dl/edgedl/chromeos/recovery/recovery.conf

**Comment by imperador** [comment]
Read the guide, it's a recovery image. Don't create issues for this

**Comment by GuzioMG** [comment]
https://cros-updates-serving.appspot.com/
Then hit Ctrl + F and type "caroline".
By the way, the site is loading incredibly long.
