### ISSUE TITLE
Graphics incompatible

### ISSUE THREAD

**Issue by fedrenfg** [imperador/chromefy#96]
Using method 1 I created .img using ATB 74+Eve+Caroline .Got stuck at Google boot logo .
Simple trying ATB 74 worked .Tried simply fydeos but it too got stuck. After googling figured out (not sure)
Intel core 2 duo with G33 graphics may cause problem.Is that right and which ATB will be best for me. 
One more question-
How can I use Emydeos ,Cloudradish insted of ATB as they contain a .bin file and script needs .IMG file?

**Comment by ningacoding** [comment]
@Ram-Benz which combination worked? for Intel core 2 duo

**Comment by Greasy-Monkey** [comment]
@ningacoding none sadly; you can just try running chromium os - the processor is completely unsupported
