### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by goshawk22** [imperador/chromefy#97]
I get the error 
`'/home/chronos/local/boot/syslinux/default.cfg' -> '/home/chronos/RAW/boot/syslinux/default.cfg'
'/home/chronos/local/boot/syslinux/root.B.cfg' -> '/home/chronos/RAW/boot/syslinux/root.B.cfg'
'/home/chronos/local/boot/syslinux/usb.A.cfg' -> '/home/chronos/RAW/boot/syslinux/usb.A.cfg'
'/home/chronos/local/boot/syslinux/README' -> '/home/chronos/RAW/boot/syslinux/README'
'/home/chronos/local/boot/syslinux/root.A.cfg' -> '/home/chronos/RAW/boot/syslinux/root.A.cfg'
'/home/chronos/local/boot/efi' -> '/home/chronos/RAW/boot/efi'
'/home/chronos/local/boot/efi/boot' -> '/home/chronos/RAW/boot/efi/boot'
'/home/chronos/local/boot/efi/boot/grub.cfg' -> '/home/chronos/RAW/boot/efi/boot/grub.cfg'
'/home/chronos/local/boot/efi/boot/bootx64.efi' -> '/home/chronos/RAW/boot/efi/boot/bootx64.efi'
'/home/chronos/local/boot/efi/boot/bootia32.efi' -> '/home/chronos/RAW/boot/efi/boot/bootia32.efi'
cp: cannot stat '/home/chronos/local/usr/lib64/dri': No such file or directory
cp: cannot stat '/home/chronos/local/usr/lib64/va': No such file or directory
Error while copying ChromiumOS files locally (insufficent disk space?)
aborting...`
even though I have over 50gb free disk space. I have tried running it on Ubuntu and Cloudready.

**Comment by goshawk22** [comment]
Sorry should have said.
I am using pyro and caroline

**Comment by goshawk22** [comment]
Sorry it seems it was because I was not using the special build of arnold the bat which is a .bin file.

**Comment by NicolasGuilloux** [comment]
I just mention again the link from which you can download the good ChromiumOS image: https://chromium.arnoldthebat.co.uk/index.php?dir=special&order=modified&sort=desc

I was confused too because I downloaded previously a `.img` file from ArnoldTheBat aswell. But thanks to you, I noticed that this was the wrong file ^^ Thanks buddy :)

**Comment by goshawk22** [comment]
You're welcome!!

**Comment by homemaint** [comment]
I still cannot find the bin file in the mentioned link above.

**Comment by regiscamimura** [comment]
same here, where is the bin file?

**Comment by goshawk22** [comment]
It's compressed. Donload the correct version and unzip it.
